# Generated by Django 4.2 on 2023-04-24 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_used'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Used',
            new_name='Use',
        ),
    ]
