# Generated by Django 4.2 on 2023-04-24 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_used_use'),
    ]

    operations = [
        migrations.RenameField(
            model_name='use',
            old_name='meal',
            new_name='reason',
        ),
    ]
