# Generated by Django 4.2 on 2023-04-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_meal_use_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='use',
            name='date',
            field=models.DateField(verbose_name='Date Used'),
        ),
    ]
