# Generated by Django 4.2 on 2023-04-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_use_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Villain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='use',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='stone',
            name='villains',
            field=models.ManyToManyField(to='main_app.villain'),
        ),
    ]
